name: Call Backup API Every 5 Hours

on:
  schedule:
    - cron: '0 */5 * * *'  # Run every 5 hours (UTC)
  workflow_dispatch:        # Allow manual trigger from GitHub UI

jobs:
  call-backup-api:
    runs-on: ubuntu-latest

    steps:
      - name: Call Backup API
        run: |
          echo "📡 Calling backup API..."
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" "https://minkhant.singapore2dmm.com/backup.php")

          echo "🔁 Response status: $RESPONSE"

          if [ "$RESPONSE" -eq 200 ]; then
            echo "✅ Backup API call was successful."
          else
            echo "❌ Backup API call failed with status code $RESPONSE"
            exit 1
          fi
